In [1]:
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8777e-42, 0.0000e+00],
        [0.0000e+00, 2.5385e+30, 0.0000e+00]])


In [4]:
x = torch.rand(5, 3)

In [5]:
x

tensor([[0.8664, 0.3584, 0.4090],
        [0.8561, 0.6596, 0.2814],
        [0.9344, 0.6263, 0.9204],
        [0.4413, 0.4196, 0.0227],
        [0.7954, 0.1028, 0.8936]])

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)

In [7]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = torch.tensor([5.5, 3])

In [9]:
x

tensor([5.5000, 3.0000])

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)

In [11]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [12]:
x = torch.randn_like(x, dtype=torch.float)

In [13]:
x

tensor([[ 0.2192,  0.1409, -1.1324],
        [ 0.9365, -0.7710,  0.5258],
        [ 0.8186,  0.3731, -1.0749],
        [ 0.8021,  0.6850,  0.9333],
        [-0.9969,  0.1128,  0.4456]])

In [14]:
x.size()

torch.Size([5, 3])

## テンソルの演算

In [15]:
y = torch.rand(5, 3)

In [16]:
y

tensor([[0.6157, 0.7831, 0.3448],
        [0.3758, 0.7114, 0.3225],
        [0.4725, 0.8650, 0.4545],
        [0.7840, 0.3299, 0.5433],
        [0.5716, 0.6573, 0.2430]])

In [17]:
x + y

tensor([[ 0.8348,  0.9240, -0.7876],
        [ 1.3123, -0.0596,  0.8482],
        [ 1.2911,  1.2382, -0.6204],
        [ 1.5860,  1.0149,  1.4765],
        [-0.4253,  0.7701,  0.6886]])

In [18]:
torch.add(x, y)

tensor([[ 0.8348,  0.9240, -0.7876],
        [ 1.3123, -0.0596,  0.8482],
        [ 1.2911,  1.2382, -0.6204],
        [ 1.5860,  1.0149,  1.4765],
        [-0.4253,  0.7701,  0.6886]])

In [19]:
result = torch.empty(5, 3)

In [20]:
result

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.9170e-42, 0.0000e+00],
        [0.0000e+00, 9.9160e+27, 0.0000e+00]])

In [21]:
torch.add(x, y, out=result)

tensor([[ 0.8348,  0.9240, -0.7876],
        [ 1.3123, -0.0596,  0.8482],
        [ 1.2911,  1.2382, -0.6204],
        [ 1.5860,  1.0149,  1.4765],
        [-0.4253,  0.7701,  0.6886]])

In [22]:
y.add_(x)

tensor([[ 0.8348,  0.9240, -0.7876],
        [ 1.3123, -0.0596,  0.8482],
        [ 1.2911,  1.2382, -0.6204],
        [ 1.5860,  1.0149,  1.4765],
        [-0.4253,  0.7701,  0.6886]])

In [23]:
x[:, 1]

tensor([ 0.1409, -0.7710,  0.3731,  0.6850,  0.1128])

In [24]:
x

tensor([[ 0.2192,  0.1409, -1.1324],
        [ 0.9365, -0.7710,  0.5258],
        [ 0.8186,  0.3731, -1.0749],
        [ 0.8021,  0.6850,  0.9333],
        [-0.9969,  0.1128,  0.4456]])

## Numpyとの連携

In [26]:
a = torch.ones(5)

In [27]:
a

tensor([1., 1., 1., 1., 1.])

In [28]:
b = a.numpy()

In [29]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [30]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [31]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

### NumpyからTorchテンソルへ

In [32]:
import numpy as np

In [33]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [34]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)